activemq:
  image: codinginfinity/alpine-activemq
  ports:
      - 1883:1883
      - 5672:5672
      - 8161:8161
      - 61613:61613
      - 61614:61614
      - 61616:61616

elasticsearch:
  image: elasticsearch:1.5.2
  ports:
      - 9200:9200
      - 9300:9300

postgresql:
  image: postgres:9.4.9
  ports:
      - 5432:5432

benchmark-management:
  image: codinginfinity/benchmark-management
  ports:
      - 8081:8081
  links:
      - activemq
      - elasticsearch
      - postgresql
  environment:
      - SPRING_PROFILES_ACTIVE=prod

benchmark-web-interface:
    image: codinginfinity/web-interface
    ports:
        - 80:80
    links:
        - benchmark_management