# ===================================================================
# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
       active: dev
    datasource:
        schema: classpath:schema.sql
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# Benchmark Managament Server specific properties
# ===================================================================

benchmark:
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    mail:
        from: benchmark-service@cs.up.ac.za
    swagger:
        title: Benchmark Management Server API
        description: Benchmark Management Server API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName: Vreda Pieterse
        contactUrl: http://www.cs.up.ac.za/~vpieterse/
        contactEmail: vpieterse@cs.up.ac.za
        license: AGPLv3
        licenseUrl: https://www.gnu.org/licenses/agpl-3.0.en.html
    frontend:
        baseUrl: localhost:8080

server:
  port: 8081

multipart:
  maxFileSize: 10000MB
  maxRequestSize: 10000MB
