# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    datasource:
        url: jdbc:postgresql://postgresql:5432/postgres
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: elasticsearch:9300
    thymeleaf:
        cache: true
    activemq:
        broker-url: tcp://activemq:61616
        in-memory: false
        pooled: false
    mail:
        host: localhost
        port: 25
        test-connection: false

liquibase:
    contexts: prod

server:
    port: 8081
    compression:
        enabled: true
        mime-types: text/plain,application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# Benchmark Managament Server specific properties
# ===================================================================

benchmark:
    security:
        authentication:
            oauth:
                clientid: acme
                secret: acmesecret
                # Token is valid 30 minutes
                tokenValidityInSeconds: 1800
    swagger:
        enabled: false